# Test suite authors. We derive their names (keys) from the initial
# Git check-in and map them to their LDAP names.
#
SureshVoora: suresh
prashanth: padubiry
amallina: arunamallina
Arun.Mallina: arunamallina
Vui Le: vui
Animesh Patcha: animesh
songbeng: slim
tomaszklimczyk: tomasz
Tomasz Klimczyk: tomasz
Mingtao Yang: mingtao
Don Jayakody: don
Don: don
Cliff DeGuzman: cliff
kranti: kranti
krantiln: kranti
William Tan: wtan
fc7737: wtan
Sakshi Kalra: sakshikalra
Unknown: unknown
sahaja: ksahaja
ksahaja: ksahaja
Ivan Lum: ilum
ivansfo: ilum